on:
  push:
    branches: [ 'main' ]

env:
  MOBILEPAY_API_KEY: ${{ secrets.MOBILEPAY_API_KEY }}
  MOBILEPAY_PAYMENTPOINT_ID: ${{ secrets.MOBILEPAY_PAYMENTPOINT_ID }}
  MOBILEPAY_PAYMENT_SOURCE_ID: ${{ secrets.MOBILEPAY_PAYMENT_SOURCE_ID }}
  MOBILEPAY_USER_ID: ${{ secrets.MOBILEPAY_USER_ID }}

name: "Main"

jobs:

  tests:
    name: "Tests on PHP ${{ matrix.php-version }} ${{ matrix.prefer-lowest }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.1', '8.2' ]
        prefer-lowest: ['', '--prefer-lowest --prefer-stable']
        coverage-driver: [ 'xdebug' ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: "Install dependencies"
        run: composer update ${{ matrix.prefer-lowest }} --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        run: make tests-e2e
